run:
  timeout: 5m

  build-tags:
    - e2e

linters:
  enable:
    - errorlint
    - unconvert
    - unparam
    - prealloc
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - unparam
